AWSTemplateFormatVersion: "2010-09-09"
Resources:
  mindfulMessages:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mindful-messages
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"

      ProvisionedThroughput:
        ReadCapacityUnits: "10"
        WriteCapacityUnits: "5"